0x30:
  entityID: 0x06
  entityInstance: 1
  sensorType: 0x01
  path: /xyz/openbmc_project/sensors/temperature/KL0
  sensorReadingType: 0x01
  bExp: 0
  rExp: 0
  scale: -3
  mutability: Mutability::Write|Mutability::Read
  serviceInterface: org.freedesktop.DBus.Properties
  readingType: readingData
  sensorNamePattern: nameLeaf
  unit: xyz.openbmc_project.Sensor.Value.Unit.DegreesC
  interfaces:
    xyz.openbmc_project.Sensor.Value:
      Value:
        Offsets:
          0xFF:
            type: int64_t

0x31:
  entityID: 0x0D
  entityInstance: 1
  sensorType: 0x01
  path: /xyz/openbmc_project/sensors/temperature/KL1
  sensorReadingType: 0x01
  bExp: 0
  rExp: 0
  scale: -3
  mutability: Mutability::Write|Mutability::Read
  serviceInterface: org.freedesktop.DBus.Properties
  readingType: readingData
  sensorNamePattern: nameLeaf
  unit: xyz.openbmc_project.Sensor.Value.Unit.DegreesC
  interfaces:
    xyz.openbmc_project.Sensor.Value:
      Value:
        Offsets:
          0xFF:
            type: int64_t

0x32:
  entityID: 0x0E
  entityInstance: 1
  sensorType: 0x01
  path: /xyz/openbmc_project/sensors/temperature/KL2
  sensorReadingType: 0x01
  bExp: 0
  rExp: 0
  scale: -3
  mutability: Mutability::Write|Mutability::Read
  serviceInterface: org.freedesktop.DBus.Properties
  readingType: readingData
  sensorNamePattern: nameLeaf
  unit: xyz.openbmc_project.Sensor.Value.Unit.DegreesC
  interfaces:
    xyz.openbmc_project.Sensor.Value:
      Value:
        Offsets:
          0xFF:
            type: int64_t

0x33:
  entityID: 0x0E
  entityInstance: 2
  sensorType: 0x01
  path: /xyz/openbmc_project/sensors/temperature/KL3
  sensorReadingType: 0x01
  bExp: 0
  rExp: 0
  scale: -3
  mutability: Mutability::Write|Mutability::Read
  serviceInterface: org.freedesktop.DBus.Properties
  readingType: readingData
  sensorNamePattern: nameLeaf
  unit: xyz.openbmc_project.Sensor.Value.Unit.DegreesC
  interfaces:
    xyz.openbmc_project.Sensor.Value:
      Value:
        Offsets:
          0xFF:
            type: int64_t

0x3C:
  entityID: 0x0A
  entityInstance: 1
  sensorType: 0x01
  path: /xyz/openbmc_project/sensors/temperature/P48V_HSC_Temp
  sensorReadingType: 0x01
  bExp: 0
  rExp: 0
  scale: -3
  mutability: Mutability::Write|Mutability::Read
  serviceInterface: org.freedesktop.DBus.Properties
  readingType: readingData
  sensorNamePattern: nameLeaf
  unit: xyz.openbmc_project.Sensor.Value.Unit.DegreesC
  interfaces:
    xyz.openbmc_project.Sensor.Value:
      Value:
        Offsets:
          0xFF:
            type: int64_t
0x70:
  entityID: 0x0A
  entityInstance: 5
  sensorType: 0x03
  path: /xyz/openbmc_project/sensors/current/P48V_HSC_Current
  sensorReadingType: 0x01
  multiplierM: 9
  offsetB: 0
  bExp: 0
  rExp: -2
  scale: -3
  mutability: Mutability::Write|Mutability::Read
  serviceInterface: org.freedesktop.DBus.Properties
  readingType: readingData
  sensorNamePattern: nameLeaf
  unit: xyz.openbmc_project.Sensor.Value.Unit.Amperes
  interfaces:
    xyz.openbmc_project.Sensor.Value:
      Value:
        Offsets:
          0xFF:
            type: int64_t

0x60:
  entityID: 0x0A
  entityInstance: 3
  sensorType: 0x02
  path: /xyz/openbmc_project/sensors/voltage/P48V_HSC_Vol
  sensorReadingType: 0x01
  multiplierM: 243
  offsetB: 0
  bExp: 0
  rExp: -3
  scale: -3
  mutability: Mutability::Write|Mutability::Read
  serviceInterface: org.freedesktop.DBus.Properties
  readingType: readingData
  sensorNamePattern: nameLeaf
  unit: xyz.openbmc_project.Sensor.Value.Unit.Volts
  interfaces:
    xyz.openbmc_project.Sensor.Value:
      Value:
        Offsets:
          0xFF:
            type: int64_t

0x90:
  entityID: 0x0A
  entityInstance: 6
  sensorType: 0x0B
  path: /xyz/openbmc_project/sensors/power/P48V_HSC_Power
  sensorReadingType: 0x01
  multiplierM: 310
  offsetB: 4
  bExp: 2
  rExp: -2
  scale: -6
  mutability: Mutability::Write|Mutability::Read
  serviceInterface: org.freedesktop.DBus.Properties
  readingType: readingData
  sensorNamePattern: nameLeaf
  unit: xyz.openbmc_project.Sensor.Value.Unit.Watts
  interfaces:
    xyz.openbmc_project.Sensor.Value:
      Value:
        Offsets:
          0xFF:
            type: int64_t

0x3D:
  entityID: 0x0A
  entityInstance: 2
  sensorType: 0x01
  path: /xyz/openbmc_project/sensors/temperature/P12V_BRIC_Temp
  sensorReadingType: 0x01
  bExp: 0
  rExp: 0
  scale: -3
  mutability: Mutability::Write|Mutability::Read
  serviceInterface: org.freedesktop.DBus.Properties
  readingType: readingData
  sensorNamePattern: nameLeaf
  unit: xyz.openbmc_project.Sensor.Value.Unit.DegreesC
  interfaces:
    xyz.openbmc_project.Sensor.Value:
      Value:
        Offsets:
          0xFF:
            type: int64_t
0x71:
  entityID: 0x0A
  entityInstance: 7
  sensorType: 0x03
  path: /xyz/openbmc_project/sensors/current/P12V_BRIC_Current
  sensorReadingType: 0x01
  multiplierM: 200
  offsetB: 0
  bExp: 0
  rExp: -3
  scale: -3
  mutability: Mutability::Write|Mutability::Read
  serviceInterface: org.freedesktop.DBus.Properties
  readingType: readingData
  sensorNamePattern: nameLeaf
  unit: xyz.openbmc_project.Sensor.Value.Unit.Amperes
  interfaces:
    xyz.openbmc_project.Sensor.Value:
      Value:
        Offsets:
          0xFF:
            type: int64_t

0x61:
  entityID: 0x0A
  entityInstance: 4
  sensorType: 0x02
  path: /xyz/openbmc_project/sensors/voltage/P12V_BRIC_Vol
  sensorReadingType: 0x01
  multiplierM: 509
  offsetB: 0
  bExp: 0
  rExp: -4
  scale: -3
  mutability: Mutability::Write|Mutability::Read
  serviceInterface: org.freedesktop.DBus.Properties
  readingType: readingData
  sensorNamePattern: nameLeaf
  unit: xyz.openbmc_project.Sensor.Value.Unit.Volts
  interfaces:
    xyz.openbmc_project.Sensor.Value:
      Value:
        Offsets:
          0xFF:
            type: int64_t


0x80:
  entityID: 0x1D
  entityInstance: 1
  sensorType: 0x04
  path: /xyz/openbmc_project/sensors/fan_tach/Fan0_0_RPM
  sensorReadingType: 0x01
  multiplierM: 100
  offsetB: 0
  bExp: 0
  rExp: 0
  unit: xyz.openbmc_project.Sensor.Value.Unit.RPMS
  scale: 0
  serviceInterface: org.freedesktop.DBus.Properties
  readingType: readingData
  sensorNamePattern: nameLeaf
  interfaces:
    xyz.openbmc_project.Sensor.Value:
      Value:
        Offsets:
          0xFF:
            type: int64_t
0x81:
  entityID: 0x1D
  entityInstance: 2
  sensorType: 0x04
  path: /xyz/openbmc_project/sensors/fan_tach/Fan0_1_RPM
  sensorReadingType: 0x01
  multiplierM: 100
  offsetB: 0
  bExp: 0
  rExp: 0
  unit: xyz.openbmc_project.Sensor.Value.Unit.RPMS
  scale: 0
  serviceInterface: org.freedesktop.DBus.Properties
  readingType: readingData
  sensorNamePattern: nameLeaf
  interfaces:
    xyz.openbmc_project.Sensor.Value:
      Value:
        Offsets:
          0xFF:
            type: int64_t
0x82:
  entityID: 0x1D
  entityInstance: 3
  sensorType: 0x04
  path: /xyz/openbmc_project/sensors/fan_tach/Fan1_0_RPM
  sensorReadingType: 0x01
  multiplierM: 100
  offsetB: 0
  bExp: 0
  rExp: 0
  unit: xyz.openbmc_project.Sensor.Value.Unit.RPMS
  scale: 0
  serviceInterface: org.freedesktop.DBus.Properties
  readingType: readingData
  sensorNamePattern: nameLeaf
  interfaces:
    xyz.openbmc_project.Sensor.Value:
      Value:
        Offsets:
          0xFF:
            type: int64_t
0x83:
  entityID: 0x1D
  entityInstance: 4
  sensorType: 0x04
  path: /xyz/openbmc_project/sensors/fan_tach/Fan1_1_RPM
  sensorReadingType: 0x01
  multiplierM: 100
  offsetB: 0
  bExp: 0
  rExp: 0
  unit: xyz.openbmc_project.Sensor.Value.Unit.RPMS
  scale: 0
  serviceInterface: org.freedesktop.DBus.Properties
  readingType: readingData
  sensorNamePattern: nameLeaf
  interfaces:
    xyz.openbmc_project.Sensor.Value:
      Value:
        Offsets:
          0xFF:
            type: int64_t
0x84:
  entityID: 0x1D
  entityInstance: 5
  sensorType: 0x04
  path: /xyz/openbmc_project/sensors/fan_tach/Fan2_0_RPM
  sensorReadingType: 0x01
  multiplierM: 100
  offsetB: 0
  bExp: 0
  rExp: 0
  unit: xyz.openbmc_project.Sensor.Value.Unit.RPMS
  scale: 0
  serviceInterface: org.freedesktop.DBus.Properties
  readingType: readingData
  sensorNamePattern: nameLeaf
  interfaces:
    xyz.openbmc_project.Sensor.Value:
      Value:
        Offsets:
          0xFF:
            type: int64_t
0x85:
  entityID: 0x1D
  entityInstance: 6
  sensorType: 0x04
  path: /xyz/openbmc_project/sensors/fan_tach/Fan2_1_RPM
  sensorReadingType: 0x01
  multiplierM: 100
  offsetB: 0
  bExp: 0
  rExp: 0
  unit: xyz.openbmc_project.Sensor.Value.Unit.RPMS
  scale: 0
  serviceInterface: org.freedesktop.DBus.Properties
  readingType: readingData
  sensorNamePattern: nameLeaf
  interfaces:
    xyz.openbmc_project.Sensor.Value:
      Value:
        Offsets:
          0xFF:
            type: int64_t

0x34:
  entityID: 0x07
  entityInstance: 1
  sensorType: 0x01
  path: /xyz/openbmc_project/nvme/1
  sensorReadingType: 0x01
  mutability: Mutability::Write|Mutability::Read
  serviceInterface: org.freedesktop.DBus.Properties
  readingType: readingData
  sensorNamePattern: nameParentLeaf
  unit: xyz.openbmc_project.Sensor.Value.Unit.DegreesC
  interfaces:
    xyz.openbmc_project.Sensor.Value:
      Value:
        Offsets:
          0xFF:
            type: int64_t
0x35:
  entityID: 0x07
  entityInstance: 2
  sensorType: 0x01
  path: /xyz/openbmc_project/nvme/2
  sensorReadingType: 0x01
  mutability: Mutability::Write|Mutability::Read
  serviceInterface: org.freedesktop.DBus.Properties
  readingType: readingData
  sensorNamePattern: nameParentLeaf
  unit: xyz.openbmc_project.Sensor.Value.Unit.DegreesC
  interfaces:
    xyz.openbmc_project.Sensor.Value:
      Value:
        Offsets:
          0xFF:
            type: int64_t
0x36:
  entityID: 0x07
  entityInstance: 3
  sensorType: 0x01
  path: /xyz/openbmc_project/nvme/3
  sensorReadingType: 0x01
  mutability: Mutability::Write|Mutability::Read
  serviceInterface: org.freedesktop.DBus.Properties
  readingType: readingData
  sensorNamePattern: nameParentLeaf
  unit: xyz.openbmc_project.Sensor.Value.Unit.DegreesC
  interfaces:
    xyz.openbmc_project.Sensor.Value:
      Value:
        Offsets:
          0xFF:
            type: int64_t
0x37:
  entityID: 0x07
  entityInstance: 4
  sensorType: 0x01
  path: /xyz/openbmc_project/nvme/4
  sensorReadingType: 0x01
  mutability: Mutability::Write|Mutability::Read
  serviceInterface: org.freedesktop.DBus.Properties
  readingType: readingData
  sensorNamePattern: nameParentLeaf
  unit: xyz.openbmc_project.Sensor.Value.Unit.DegreesC
  interfaces:
    xyz.openbmc_project.Sensor.Value:
      Value:
        Offsets:
          0xFF:
            type: int64_t
0x38:
  entityID: 0x07
  entityInstance: 5
  sensorType: 0x01
  path: /xyz/openbmc_project/nvme/5
  sensorReadingType: 0x01
  mutability: Mutability::Write|Mutability::Read
  serviceInterface: org.freedesktop.DBus.Properties
  readingType: readingData
  sensorNamePattern: nameParentLeaf
  unit: xyz.openbmc_project.Sensor.Value.Unit.DegreesC
  interfaces:
    xyz.openbmc_project.Sensor.Value:
      Value:
        Offsets:
          0xFF:
            type: int64_t
0x39:
  entityID: 0x07
  entityInstance: 6
  sensorType: 0x01
  path: /xyz/openbmc_project/nvme/6
  sensorReadingType: 0x01
  mutability: Mutability::Write|Mutability::Read
  serviceInterface: org.freedesktop.DBus.Properties
  readingType: readingData
  sensorNamePattern: nameParentLeaf
  unit: xyz.openbmc_project.Sensor.Value.Unit.DegreesC
  interfaces:
    xyz.openbmc_project.Sensor.Value:
      Value:
        Offsets:
          0xFF:
            type: int64_t
0x3A:
  entityID: 0x07
  entityInstance: 7
  sensorType: 0x01
  path: /xyz/openbmc_project/nvme/7
  sensorReadingType: 0x01
  mutability: Mutability::Write|Mutability::Read
  serviceInterface: org.freedesktop.DBus.Properties
  readingType: readingData
  sensorNamePattern: nameParentLeaf
  unit: xyz.openbmc_project.Sensor.Value.Unit.DegreesC
  interfaces:
    xyz.openbmc_project.Sensor.Value:
      Value:
        Offsets:
          0xFF:
            type: int64_t
0x3B:
  entityID: 0x07
  entityInstance: 8
  sensorType: 0x01
  path: /xyz/openbmc_project/nvme/8
  sensorReadingType: 0x01
  mutability: Mutability::Write|Mutability::Read
  serviceInterface: org.freedesktop.DBus.Properties
  readingType: readingData
  sensorNamePattern: nameParentLeaf
  unit: xyz.openbmc_project.Sensor.Value.Unit.DegreesC
  interfaces:
    xyz.openbmc_project.Sensor.Value:
      Value:
        Offsets:
          0xFF:
            type: int64_t

0xB0:
  entityID: 0x20
  entityInstance: 1
  sensorType: 0x0C
  path: /xyz/openbmc_project/memory/BmcECC
  sensorReadingType: 0x6F
  serviceInterface: org.freedesktop.DBus.Properties
  readingType: assertion
  mutability: Mutability::Read
  sensorNamePattern: nameLeaf
  interfaces:
    xyz.openbmc_project.Memory.MemoryECC:
      state:
        Offsets:
          0x00:
            type: string
            assert: xyz.openbmc_project.Sensor.Memory.MemoryECC.ECCStatus.CE
          0x01:
            type: string
            assert: xyz.openbmc_project.Sensor.Memory.MemoryECC.ECCStatus.UE
          0x05:
            type: string
            assert: xyz.openbmc_project.Sensor.Memory.MemoryECC.ECCStatus.LogFulled